repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--remove-all-unused-imports', '--recursive', '--in-place', '--remove-unused-variables']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-json
        exclude: (\.jshintrc)
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: '^customer/static/.*'  # Exclude all files under customer/static/

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: Flake8 Py3
        language_version: python3.11
